package avr.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.nodeEditor.style.Style;
import jetbrains.mps.nodeEditor.style.StyleAttributes;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.smodel.action.NodeFactoryManager;
import jetbrains.mps.nodeEditor.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.nodeEditor.cellMenu.DefaultReferenceSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class PinConfiguration_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_w101z9_a(editorContext, node);
  }

  private EditorCell createCollection_w101z9_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_w101z9_a");
    editorCell.addEditorCell(this.createConstant_w101z9_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_e0(editorContext, node));
    editorCell.addEditorCell(this.createRefNodeList_w101z9_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_h0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_i0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_w101z9_j0(editorContext, node));
    editorCell.addEditorCell(this.createRefNodeList_w101z9_k0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_w101z9_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Pin Configuration:");
    editorCell.setCellId("Constant_w101z9_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_w101z9_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "digital:");
    editorCell.setCellId("Constant_w101z9_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "-----------------------------------");
    editorCell.setCellId("Constant_w101z9_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_w101z9_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_w101z9_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "analog:");
    editorCell.setCellId("Constant_w101z9_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_i0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "-----------------------------------");
    editorCell.setCellId("Constant_w101z9_i0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_w101z9_j0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_w101z9_j0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createRefNodeList_w101z9_f0(EditorContext editorContext, SNode node) {
    AbstractCellListHandler handler = new PinConfiguration_Editor.digitalPinsListHandler_w101z9_f0(node, "digitalPins", editorContext);
    EditorCell_Collection editorCell = handler.createCells(editorContext, new CellLayout_Vertical(), false);
    editorCell.setCellId("refNodeList_digitalPins");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }

  private EditorCell createRefNodeList_w101z9_k0(EditorContext editorContext, SNode node) {
    AbstractCellListHandler handler = new PinConfiguration_Editor.analogPinsListHandler_w101z9_k0(node, "analogPins", editorContext);
    EditorCell_Collection editorCell = handler.createCells(editorContext, new CellLayout_Vertical(), false);
    editorCell.setCellId("refNodeList_analogPins");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }

  private static class digitalPinsListHandler_w101z9_f0 extends RefNodeListHandler {
    public digitalPinsListHandler_w101z9_f0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      SNode listOwner = super.getOwner();
      return NodeFactoryManager.createNode(listOwner, editorContext, super.getElementRole());
    }

    public EditorCell createNodeCell(EditorContext editorContext, SNode elementNode) {
      EditorCell elementCell = super.createNodeCell(editorContext, elementNode);
      this.installElementCellActions(this.getOwner(), elementNode, elementCell, editorContext);
      return elementCell;
    }

    public EditorCell createEmptyCell(EditorContext editorContext) {
      EditorCell emptyCell = null;
      emptyCell = super.createEmptyCell(editorContext);
      this.installElementCellActions(super.getOwner(), null, emptyCell, editorContext);
      return emptyCell;
    }

    public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext editorContext) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultReferenceSubstituteInfo) {
          elementCell.setSubstituteInfo(new DefaultChildSubstituteInfo(listOwner, elementNode, super.getLinkDeclaration(), editorContext));
        }
      }
    }
  }

  private static class analogPinsListHandler_w101z9_k0 extends RefNodeListHandler {
    public analogPinsListHandler_w101z9_k0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      SNode listOwner = super.getOwner();
      return NodeFactoryManager.createNode(listOwner, editorContext, super.getElementRole());
    }

    public EditorCell createNodeCell(EditorContext editorContext, SNode elementNode) {
      EditorCell elementCell = super.createNodeCell(editorContext, elementNode);
      this.installElementCellActions(this.getOwner(), elementNode, elementCell, editorContext);
      return elementCell;
    }

    public EditorCell createEmptyCell(EditorContext editorContext) {
      EditorCell emptyCell = null;
      emptyCell = super.createEmptyCell(editorContext);
      this.installElementCellActions(super.getOwner(), null, emptyCell, editorContext);
      return emptyCell;
    }

    public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext editorContext) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultReferenceSubstituteInfo) {
          elementCell.setSubstituteInfo(new DefaultChildSubstituteInfo(listOwner, elementNode, super.getLinkDeclaration(), editorContext));
        }
      }
    }
  }
}
