package avr.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Avr_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("70b87b6c-9896-41b4-b968-0fb3e595f4cc(avr)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
