package avr.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum DigitalValue {
  high("high", 0),
  low("low", 1);

  private String myName;
  private int myValue;

  DigitalValue(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public int getValue() {
    return this.myValue;
  }

  public static List<DigitalValue> getConstants() {
    List<DigitalValue> list = ListSequence.fromList(new LinkedList<DigitalValue>());
    ListSequence.fromList(list).addElement(DigitalValue.high);
    ListSequence.fromList(list).addElement(DigitalValue.low);
    return list;
  }

  public static DigitalValue getDefault() {
    return DigitalValue.high;
  }

  public static DigitalValue parseValue(String value) {
    if (value == null) {
      return DigitalValue.getDefault();
    }
    if (value.equals(DigitalValue.high.getValueAsString())) {
      return DigitalValue.high;
    }
    if (value.equals(DigitalValue.low.getValueAsString())) {
      return DigitalValue.low;
    }
    return DigitalValue.getDefault();
  }
}
