package avr.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Direction {
  Input("Input", false),
  Output("Output", false);

  private String myName;
  private boolean myValue;

  Direction(String name, boolean value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public boolean getValue() {
    return this.myValue;
  }

  public static List<Direction> getConstants() {
    List<Direction> list = ListSequence.fromList(new LinkedList<Direction>());
    ListSequence.fromList(list).addElement(Direction.Input);
    ListSequence.fromList(list).addElement(Direction.Output);
    return list;
  }

  public static Direction getDefault() {
    return Direction.Input;
  }

  public static Direction parseValue(String value) {
    if (value == null) {
      return Direction.getDefault();
    }
    if (value.equals(Direction.Input.getValueAsString())) {
      return Direction.Input;
    }
    if (value.equals(Direction.Output.getValueAsString())) {
      return Direction.Output;
    }
    return Direction.getDefault();
  }
}
