package avr.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"avr.structure.AnalogInput", "avr.structure.AnalogPin", "avr.structure.Arduino", "avr.structure.Arduino_Uno", "avr.structure.DigitalInput", "avr.structure.DigitalNone", "avr.structure.DigitalOutput", "avr.structure.DigitalPin", "avr.structure.DigitalPinAction", "avr.structure.DigitalValueCheck", "avr.structure.IPin", "avr.structure.PinConfiguration"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("avr.structure.AnalogInput", "avr.structure.AnalogPin", false, new String[]{"avr.structure.AnalogPin"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("avr.structure.AnalogPin", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "avr.structure.IPin"}, new String[]{}, new String[]{});
      case 2:
        return new CompiledConceptDescriptor("avr.structure.Arduino", "com.mbeddr.core.buildconfig.structure.Platform", false, new String[]{"com.mbeddr.core.buildconfig.structure.Platform"}, new String[]{"cpuSpeed", "mcu"}, new String[]{});
      case 3:
        return new CompiledConceptDescriptor("avr.structure.Arduino_Uno", "avr.structure.Arduino", false, new String[]{"avr.structure.Arduino"}, new String[]{}, new String[]{});
      case 4:
        return new CompiledConceptDescriptor("avr.structure.DigitalInput", "avr.structure.DigitalPin", false, new String[]{"avr.structure.DigitalPin"}, new String[]{}, new String[]{});
      case 5:
        return new CompiledConceptDescriptor("avr.structure.DigitalNone", "avr.structure.DigitalPin", false, new String[]{"avr.structure.DigitalPin"}, new String[]{}, new String[]{});
      case 6:
        return new CompiledConceptDescriptor("avr.structure.DigitalOutput", "avr.structure.DigitalPin", false, new String[]{"avr.structure.DigitalPin"}, new String[]{}, new String[]{});
      case 7:
        return new CompiledConceptDescriptor("avr.structure.DigitalPin", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "avr.structure.IPin"}, new String[]{"name"}, new String[]{});
      case 8:
        return new CompiledConceptDescriptor("avr.structure.DigitalPinAction", "com.mbeddr.core.expressions.structure.Expression", false, new String[]{"com.mbeddr.core.expressions.structure.Expression"}, new String[]{"action"}, new String[]{"pin"});
      case 9:
        return new CompiledConceptDescriptor("avr.structure.DigitalValueCheck", "com.mbeddr.core.expressions.structure.BooleanLiteral", false, new String[]{"com.mbeddr.core.expressions.structure.BooleanLiteral"}, new String[]{"value"}, new String[]{"input"});
      case 10:
        return new CompiledConceptDescriptor("avr.structure.IPin", null, true, new String[]{}, new String[]{"number"}, new String[]{});
      case 11:
        return new CompiledConceptDescriptor("avr.structure.PinConfiguration", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "com.mbeddr.core.base.structure.IGeneratesCodeForIDE"}, new String[]{}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
