package avr.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class PinConfiguration_Constraints extends BaseConstraintsDescriptor {
  public PinConfiguration_Constraints() {
    super("avr.structure.PinConfiguration");
  }
}
