package avr.behavior;

/*Generated by MPS */


public class AnalogInput_BehaviorDescriptor extends AnalogPin_BehaviorDescriptor {
  public AnalogInput_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.AnalogInput";
  }
}
