package avr.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class AnalogPin_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPin_BehaviorDescriptor {
  public AnalogPin_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.AnalogPin";
  }
}
