package avr.behavior;

/*Generated by MPS */

import com.mbeddr.core.buildconfig.behavior.Platform_BehaviorDescriptor;

public abstract class Arduino_BehaviorDescriptor extends Platform_BehaviorDescriptor {
  public Arduino_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.Arduino";
  }
}
