package avr.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Arduino_Uno_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "cpuSpeed", "16000000UL");
    SPropertyOperations.set(thisNode, "mcu", "atmega328p");
  }
}
