package avr.behavior;

/*Generated by MPS */

import com.mbeddr.core.buildconfig.behavior.Platform_BehaviorDescriptor;

public class Arduino_Uno_BehaviorDescriptor extends Platform_BehaviorDescriptor {
  public Arduino_Uno_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.Arduino_Uno";
  }
}
