package avr.behavior;

/*Generated by MPS */


public class Arduino_Uno_BehaviorDescriptor extends Arduino_BehaviorDescriptor {
  public Arduino_Uno_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.Arduino_Uno";
  }
}
