package avr.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"avr.structure.AnalogInput", "avr.structure.Arduino_Uno", "avr.structure.DigitalInput", "avr.structure.DigitalNone", "avr.structure.DigitalOutput", "avr.structure.DigitalPinAction", "avr.structure.DigitalValueCheck", "avr.structure.PinConfiguration"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 1:
        return new Arduino_Uno_BehaviorDescriptor();
      case 7:
        return new PinConfiguration_BehaviorDescriptor();
      case 2:
        return new DigitalInput_BehaviorDescriptor();
      case 4:
        return new DigitalOutput_BehaviorDescriptor();
      case 3:
        return new DigitalNone_BehaviorDescriptor();
      case 0:
        return new AnalogInput_BehaviorDescriptor();
      case 5:
        return new DigitalPinAction_BehaviorDescriptor();
      case 6:
        return new DigitalValueCheck_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
