package avr.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class DigitalPinAction_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public DigitalPinAction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.DigitalPinAction";
  }
}
