package avr.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.BooleanLiteral_BehaviorDescriptor;

public class DigitalValueCheck_BehaviorDescriptor extends BooleanLiteral_BehaviorDescriptor {
  public DigitalValueCheck_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.DigitalValueCheck";
  }
}
