package avr.behavior;

/*Generated by MPS */


public class DigitalNone_BehaviorDescriptor extends DigitalPin_BehaviorDescriptor {
  public DigitalNone_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.DigitalNone";
  }
}
