package avr.behavior;

/*Generated by MPS */


public class DigitalOutput_BehaviorDescriptor extends DigitalPin_BehaviorDescriptor {
  public DigitalOutput_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.DigitalOutput";
  }
}
