package avr.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public abstract class DigitalPin_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPin_BehaviorDescriptor {
  public DigitalPin_BehaviorDescriptor() {
  }

  public String virtual_getPresentation_1213877396640(SNode thisNode) {
    return DigitalPin_Behavior.virtual_getPresentation_1213877396640(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.DigitalPin";
  }
}
