package avr.behavior;

/*Generated by MPS */


public class DigitalInput_BehaviorDescriptor extends DigitalPin_BehaviorDescriptor {
  public DigitalInput_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.DigitalInput";
  }
}
