package avr.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface IPin_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
