package avr.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IGeneratesCodeForIDE_BehaviorDescriptor;

public class PinConfiguration_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IGeneratesCodeForIDE_BehaviorDescriptor {
  public PinConfiguration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "avr.structure.PinConfiguration";
  }
}
